name: 'Accept'
description: 'Triggers a scaffold repository build on AppVeyor'
inputs:
  scaffold-branch:
    description: 'The scaffold branch to build'
    required: false
  gh-token:
    description: 'A GitHub token'
    required: false
  dry-run:
    description: 'Run scaffold in dry-run mode'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
