name: 'Accept'
description: 'Triggers a scaffold repository build on AppVeyor'
inputs:
  mode:
    description: 'Method to trigger scaffold build, defaults to pr, other options are bot-review, auto and always'
    required: false
  scaffold-branch:
    description: 'The scaffold branch to build'
    required: false
  gh-token:
    description: 'A GitHub token'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
