name: "Exivity Docker Build and Push"
description: "This action builds and pushes a Docker image using the docker/build-push-action"
inputs:
  context:
    default: "."
  push:
    default: "true"
  tags:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub 
      if: ${{ env.DOCKER_USERNAME && env.DOCKER_PASSWORD }}
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
