name: "Exivity Docker Build and Push"
description: "This action builds and pushes a Docker image using the docker/build-push-action with automatic metadata tag generation"
inputs:
  context:
    description: "Build context path"
    default: "."
    required: false
  dockerfile:
    description: "Path to the Dockerfile"
    default: "./Dockerfile"
    required: false
  push:
    description: "Push image to registry"
    default: "true"
    required: false
  image:
    description: "Docker image name (e.g., ghcr.io/exivity/glass)"
    required: true
  registry:
    description: "Docker registry"
    default: "ghcr.io"
    required: false
  username:
    description: "Username for Docker registry"
    default: ${{ github.actor }}
    required: false
  password:
    description: "Password for Docker registry"
    default: ${{ github.token }}
    required: false
  platforms:
    description: "Target platforms for build (e.g., linux/amd64,linux/arm64)"
    default: "linux/amd64"
    required: false

runs:
  using: "composite"
  steps:
    - name: Login to Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.version=${{ github.ref_name }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        sbom: true
        provenance: true
        attestations: type=provenance,mode=max
