name: "Exivity Docker Build and Push"
description: "This action builds and pushes a Docker image using the docker/build-push-action with automatic metadata tag generation"
inputs:
  context:
    description: "Build context path"
    default: "."
    required: false
  dockerfile:
    description: "Path to the Dockerfile"
    default: "./Dockerfile"
    required: false
  push:
    description: "Push image to registry"
    default: "true"
    required: false
  image:
    description: "Image name"
    required: true
  builder:
    description: "The namespace of the image repository"
    required: false
  registry:
    description: "Docker registry"
    default: "ghcr.io"
    required: false
  username:
    description: "Username for Docker registry"
    required: false
  password:
    description: "Password for Docker registry"
    required: false
  platforms:
    description: "Target platforms for build (e.g., linux/amd64,linux/arm64)"
    default: "linux/amd64,linux/arm64"
    required: false
  secrets:
    description: "List of secrets to expose to the build (e.g., id=mypassword,src=./secret.txt)"
    required: false
  ssh:
    description: "SSH agent socket or keys to expose to the build"
    required: false
  target:
    description: "Sets the target stage to build"
    required: false

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username || github.actor }}
        password: ${{ inputs.password || github.token }}

    - name: Set up QEMU
      uses: exivity/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: exivity/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: exivity/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.version=${{ github.ref_name }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Build and push
      uses: exivity/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        secrets: ${{ inputs.secrets }}
        ssh: ${{ inputs.ssh }}
        target: ${{ inputs.target }}
        sbom: true
        provenance: mode=max
        builder: ${{ inputs.builder }}
