name: retag-image
description: pulls, tags, and pushes a component image with multi-arch support
inputs:
  # source inputs
  source-registry:
    description: Source image registry
    required: true
    default: ghcr.io
  source-namespace:
    description: Source image namespace
    required: false
  source-name:
    description: Source image name
    required: false
  source-tag:
    description: Source image tag
    required: true
  source-user:
    description: Username for source registry
    required: false
    default: ${{ github.actor }}
  source-password:
    description: Password for source registry
    required: false
    default: ${{ github.token }}
  # target inputs
  target-registry:
    description: Target image registry
    required: true
    default: docker.io
  target-namespace:
    description: Target image namespace
    required: false
  target-name:
    description: Target image name
    required: false
  target-tag:
    description: Target image tag
    required: true
  target-user:
    description: Username for target registry
    required: false
  target-password:
    description: Password for target registry
    required: false
  multi-arch:
    description: Enable multi-arch support using buildx imagetools
    required: false
    default: 'true'
runs:
  using: node20
  main: dist/index.js
