name: deploy-image
description: Builds and deploys a component image
inputs:
  component:
    description: Component name to build the image for
    required: false
  docker-hub-user:
    description: Username for Docker Hub
    required: true
  docker-hub-password:
    description: Password for Docker Hub
    required: true
  ghcr-user:
    description: Username for GitHub Container Registry
    required: false
  ghcr-password:
    description: Password for GitHub Container Registry
    required: false
    default: ${{ github.token }}
  dockerfile:
    description: Path to the Dockerfile, defaults to ./Dockerfile
    required: false
  gh-token:
    description: The github token to delete image tags (only for 'delete' event)
    required: false
    default: ${{ github.token }}
  dry-run:
    description: Do not deploy build artefacts
    required: false
runs:
  using: node16
  main: dist/index.js
