name: slack
description: Send a Slack message
inputs:
  message:
    description: The message body to send
    required: true
  status:
    description: Include a status message
    required: false
  channel:
    description: Send message to this channel instead of commit author
    required: false
  fallback-channel:
    description: Use this channel as a fallback
    required: false
    default: '#builds'
  slack-api-token:
    description: Slack API key
    required: true
  gh-token:
    description: GitHub token with read access to the repository
    required: false
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js
