name: slack
description: Send a Slack message
inputs:
  message:
    description: The message body to send
    required: true
  channel:
    description: Send message to this channel
    required: false
  mention:
    description: Mention this user
    required: false
  component:
    description: The component for message context
    required: false
  sha:
    description: Sha of commit for message context
    required: false
  gh-token:
    description: A GitHub token with read access to the component
    required: false
  slack-api-token:
    description: Slack API key
    required: true
runs:
  using: node16
  main: dist/index.js
