name: "Exivity Docker Metadata Wrapper"
description: "Generates Docker tags and labels using docker/metadata-action"

inputs:
  images:
    required: true
  flavor:
    description: "Tag flavor config (default: latest=true)"
    required: false
    default: |
      latest=false

runs:
  using: "composite"
  steps:
    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=sha
        flavor: ${{ inputs.flavor }}

outputs:
  tags:
    description: "Generated image tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "Generated image labels"
    value: ${{ steps.meta.outputs.labels }}
