name: 'DB'
description: 'Runs a PostgreSQL docker container, create a new database, pulls in the `db` repository migrations and runs them.'
inputs:
  branch:
    description: 'The db repository branch to use'
    required: false
  db-name:
    description: 'The db name to create'
    required: false
  mode:
    description: Run as a Docker container or start the host server
    required: false
  version:
    description: 'PostgreSQL version'
    required: false
  aws-access-key-id:
    description: 'The AWS access key ID'
    required: false
  aws-secret-access-key:
    description: 'The AWS secret access key'
    required: false
  gh-token:
    description: 'A GitHub token'
    required: false
    default: ${{ github.token }}
  password:
    description: 'The password of the postgres user, only works with host mode'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
