name: 'Deploy Docker'
description: Deploys the build to docker
inputs:
  component:
    description: 'Component name to build the image for'
    required: false
  docker-hub-user:
    description: Username for Docker Hub
    required: true
  docker-hub-password:
    description: Password for Docker Hub
    required: true
  ghcr-user:
    description: Username for GitHub Container Registry
    required: true
  ghcr-password:
    description: Password for GitHub Container Registry
    required: true
  dockerfile:
    description: Path to the Dockerfile, defaults to ./Dockerfile
    required: false
  dry-run:
    description: Do not deploy build artefacts
    required: false
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: 'node12'
  main: 'dist/index.js'
