name: docker-retag-image
description: Builds and pushes a component image
inputs:
  registry:
    description: The Docker registry to use
    required: false
    default: ghcr.io
  user:
    description: Username for Docker registry
    required: false
    default: ${{ github.actor }}
  password:
    description: Password for Docker registry
    required: false
    default: ${{ github.token }}
  oldTag:
    description: Tag to remove when retagging
    required: false
    default: main
  newTag:
    description: Tag to add when retagging
    required: true
runs:
  using: node16
  main: dist/index.js
