name: 'sentinel'
description: 'The ultimate repo overwatch'
inputs:
  gh-token:
    description: A GitHub token with access to repositories
    required: false
    default: ${{ github.token }}
  mode:
    description: 'Mode of operation: analyse or update'
    required: false
    default: 'analyse'
  search-pattern:
    description:
      'The pattern to search for in workflow files (e.g., ubuntu-latest)'
    required: false
    default: ''
  replace-pattern:
    description:
      'The pattern to replace the search pattern with (e.g., ubuntu-22.04)'
    required: false
    default: ''
  file-regex:
    description:
      'The regex pattern to search for in file names (e.g.,
      (kubernetes|deploy)\.yml)'
    required: false
    default: ''
  repo-list:
    description:
      'A comma-separated list of repositories to update, if none are given, all
      repositories will be updated'
    required: false
    default: ''
  is-test:
    description: 'Set to true to run in test mode'
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: 'dist/index.js'
