name: 'Dex'
description: 'Runs a dex command'
inputs:
  cmd:
    description: 'Dex command'
    required: true
  cwd:
    description: 'Working directory'
    required: false
  mode:
    description: Run as a Docker container or use binary
    required: false
  tag:
    description: 'Docker tag to use'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
