name: 'Dex'
description: 'Runs a dex command'
inputs:
  args:
    description: 'Dex args'
    required: true
  tag:
    description: 'Docker tag to use'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
