name: push-image-ghcr
description: Builds and deploys a component image
inputs:
  component:
    description: Component name to build the image for
    required: false
  dockerfile:
    description: Path to the Dockerfile, defaults to ./Dockerfile
    required: false
runs:
  using: node16
  main: dist/index.js
