name: 'PostgreSQL'
description: 'Starts a PostgreSQL server'
inputs:
  mode:
    description: Run as a Docker container or start the host server
    required: false
  version:
    description: 'PostgreSQL version'
    required: false
  password:
    description: 'The password of the postgres user, only works with host mode'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
