name: 'PostgreSQL'
description: 'Starts a PostgreSQL server'
inputs:
  mode:
    description: Run as a Docker container or start the host server
    required: false
  version:
    description: 'PostgreSQL version'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
