name: release-notes
description: Ensures your feat/fix commits will have release notes associated
inputs:
  gh-token:
    description: GitHub token with read access to the repository
    required: false
    default: ${{ github.token }}
  jira-username:
    description: The Jira username (required in prepare and release mode)
    required: false
  jira-token:
    description: The Jira token (required in prepare and release mode)
    required: false
runs:
  using: node20
  main: dist/index.js
