name: virustotal
description: Analyse artefacts with VirusTotal
inputs:
  mode:
    description: Whether to analyse artefacts or check the analysis status
    required: false
    default: analyse
  path:
    description: The path to the file to analyse, glob patterns allowed. Required when `mode` is set to `analyse`.
  virustotal-api-key:
    description: The VirusTotal API key
    required: true
  gh-token:
    description: GitHub token used for writing commit status
    required: false
runs:
  using: node16
  main: dist/index.js
