name: accept test

on:
  push:
    paths:
      - '.github/workflows/accept-test.yml'
      - 'accept/**'
      - 'lib/github.ts'

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - run: echo 'Hello world!'
