name: accept

on:
  push:
    paths:
      - '.github/workflows/accept.yml'
      - 'accept/**'
      - 'lib/github.ts'
  pull_request:
    types: [review_requested]
  workflow_run:
    workflows: ['accept-test']
    types: [completed]

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./accept
        with:
          dry-run: true

  test-filter:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./accept
        with:
          filter: non_existing_folder/**
          dry-run: true
