name: accept

on:
  push:
    paths:
      - '.github/workflows/accept.yml'
      - 'accept/**'
      - 'lib/github.ts'
  check_run:
    types: [completed]
  status:
  pull_request:
    types: [review_requested]

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        mode: [auto, bot-review, pr, always]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./accept
        with:
          dry-run: true
          mode: ${{ matrix.mode }}
