name: approve-and-automerge-dependabot-prs

on: pull_request

permissions: write-all

jobs:
  approve-and-automerge-dependabot-prs:
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./enable-automerge
      - uses: ./review
