name: build-push-image_test

on:
  push:
    paths:
      - '.github/workflows/build-push-image_test.yml'
      - 'build-push-image/**'
      - 'lib/core.ts'
      - 'lib/github.ts'
      - 'lib/image.ts'

jobs:
  build-push-image_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build-push-image
        with:
          component: actions-test
          dockerfile: fixtures/hello/Dockerfile
