name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'yarn.lock'
      - '**/*.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
