name: build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache-dependency-path: package.json
          cache: 'yarn'

      - run: yarn
      - run: yarn build
