name: build-push-image

on:
  push:
    paths:
      - '.github/workflows/build-push-image.yml'
      - 'build-push-image/**'
      - 'lib/core.ts'
      - 'lib/github.ts'
      - 'lib/image.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./build-push-image
        with:
          component: actions-test
          dockerfile: fixtures/Dockerfile
