name: commit-status_test

on:
  push:
    paths:
      - '.github/workflows/commit-status_test.yml'
      - 'commit-status/**'
      - 'lib/github.ts'

jobs:
  commit-status_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./commit-status
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          context: auto-success
