name: db

on:
  push:
    paths:
      - '.github/workflows/db.yml'
      - 'lib/postgres*'
      - 'lib/docker*'
      - 'lib/github*'
      - 'lib/s3*'
      - 'db/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        mode: [host, docker]
        version: ['12.3']
        include:
          # Docker supports more versions
          - mode: docker
            version: '13.0'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./db
        with:
          mode: ${{ matrix.mode }}
          version: ${{ matrix.version }}
