name: db

on:
  push:
    paths:
      - '.github/workflows/db.yml'
      - 'lib/postgres*'
      - 'lib/docker*'
      - 'lib/github*'
      - 'lib/s3*'
      - 'db/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test-docker:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./db
        with:
          mode: docker

  test-host:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./db
        with:
          mode: host
