name: delete-package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to delete
        required: true
  delete:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./delete-package
        with:
          component: actions-test
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
