name: deploy-docker

on:
  push:
    paths:
      - '.github/workflows/deploy-docker.yml'
      - 'lib/core*'
      - 'lib/github*'
      - 'lib/s3*'
      - 'deploy-docker/**'

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./deploy-docker
        with:
          component: actions-test
          dockerfile: fixtures/Dockerfile
          docker-hub-user: ${{ secrets.DOCKER_HUB_USER }}
          docker-hub-password: ${{ secrets.DOCKER_HUB_TOKEN }}
          ghcr-user: ${{ github.actor }}
          ghcr-password: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
