name: deploy-image-cleanup

on: delete

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./deploy-image
        with:
          component: actions-test
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
