name: dummy-data_test

on:
  push:
    paths:
      - '.github/workflows/dummy-data_test.yml'
      - 'dummy-data/**'
      - 'lib/github.ts'

env:
  EXIVITY_HOME_PATH: ${{ github.workspace }}/exivity/home
  EXIVITY_PROGRAM_PATH: ${{ github.workspace }}/exivity/program

jobs:
  dummy-data_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: create exivity dirs
        run: |
          mkdir -p ${{ env.EXIVITY_HOME_PATH }}
          mkdir -p ${{ env.EXIVITY_PROGRAM_PATH }}
      - uses: ./db
        with:
          branch: main
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
      - uses: ./dummy-data
        continue-on-error: true
