name: enable-automerge_test

on:
  push:
    paths:
      - '.github/workflows/enable-automerge_test.yml'
      - 'enable-automerge/**'
      - 'lib/github.ts'

jobs:
  enable-automerge_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./enable-automerge
