name: get-artefacts

on:
  push:
    paths:
      - '.github/workflows/get-artefacts.yml'
      - 'lib/core*'
      - 'lib/github.ts'
      - 'lib/s3*'
      - 'get-artefacts/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./get-artefacts
        with:
          component: actions
          branch: master
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
