name: get-artefacts

on:
  push:
    paths:
      - '.github/workflows/get-artefacts.yml'
      - 'lib/core*'
      - 'lib/github*'
      - 'lib/s3*'
      - 'get-artefacts/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./get-artefacts
        with:
          component: actions
          branch: master
