name: get-artefacts_test

on:
  push:
    paths:
      - '.github/workflows/get-artefacts_test.yml'
      - 'lib/core*'
      - 'lib/github.ts'
      - 'lib/s3*'
      - 'get-artefacts/**'

jobs:
  get-artefacts_test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./get-artefacts
        with:
          component: actions
          branch: master
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
