name: hello-world_fixture

on:
  workflow_dispatch:
  push:
    paths:
      - 'accept/**'

jobs:
  hello-world_fixture:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo "Hello World!\n$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
