name: init-ssh

on:
  push:
    paths:
      - '.github/workflows/init-ssh.yml'
      - 'init-ssh/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./init-ssh
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: bash init-ssh/test.sh
        env:
          USERNAME: exivity-bot
