name: init-ssh_test

on:
  push:
    paths:
      - '.github/workflows/init-ssh_test.yml'
      - 'init-ssh/**'

jobs:
  init-ssh_test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./init-ssh
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: bash init-ssh/test.sh
        env:
          USERNAME: exivity-bot
