name: init-ssh

on:
  push:
    paths:
      - '.github/workflows/init-ssh.yml'
      - 'init-ssh/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./init-ssh
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: (ssh git@github.com 2>&1 | grep "exivity-bot") || ssh -vvv git@github.com
        shell: bash
