name: postgres

on:
  push:
    paths:
      - '.github/workflows/postgres.yml'
      - 'lib/postgres*'
      - 'lib/docker*'
      - 'postgres/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        mode: [host, docker]
        version: ['12.3', '13.0', '14.0']
        exclude:
          # Only default version is supported with mode=host
          - mode: host
            version: '12.3'
          - mode: host
            version: '13.0'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./postgres
        with:
          mode: ${{ matrix.mode }}
          version: ${{ matrix.version }}
