name: postgres

on:
  push:
    paths:
      - '.github/workflows/postgres.yml'
      - 'lib/postgres*'
      - 'lib/docker*'
      - 'postgres/**'

jobs:
  test-docker:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./postgres
        with:
          mode: docker

  test-host:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./postgres
        with:
          mode: host
