name: postgres

on:
  push:
    paths:
      - '.github/workflows/postgres.yml'
      - 'lib/**'
      - 'postgres/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./postgres
