name: purge-ghcr_test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to delete
        required: true
  delete:

jobs:
  purge-ghcr_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./purge-ghcr
        with:
          component: actions-test
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
