name: put-artefacts

on:
  push:
    paths:
      - '.github/workflows/put-artefacts.yml'
      - 'lib/s3*'
      - 'put-artefacts/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./put-artefacts
        with:
          path: fixtures/build
