name: put-artefacts_test

on:
  push:
    paths:
      - '.github/workflows/put-artefacts_test.yml'
      - 'lib/core*'
      - 'lib/s3*'
      - 'put-artefacts/**'

jobs:
  put-artefacts_test:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        zip: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./put-artefacts
        with:
          path: fixtures/hello/build
          zip: ${{ matrix.zip }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
