name: rabbitmq

on:
  push:
    paths:
      - '.github/workflows/rabbitmq.yml'
      - 'lib/docker*'
      - 'rabbitmq/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./rabbitmq
