name: rabbitmq_test

on:
  push:
    paths:
      - '.github/workflows/rabbitmq_test.yml'
      - 'lib/docker*'
      - 'rabbitmq/**'

jobs:
  rabbitmq_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./rabbitmq
