name: rabbitmq

on:
  push:
    paths:
      - 'rabbitmq/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./rabbitmq
