name: rcedit_test

on:
  push:
    paths:
      - '.github/workflows/rcedit_test.yml'
      - 'rcedit/**'

jobs:
  rcedit_test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./rcedit
        with:
          path: fixtures/build/*.exe
      - uses: actions/upload-artifact@v3
        with:
          path: fixtures/build/*.exe
