name: release_test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/release_test.yml'
      - 'lib/github.ts'
      - 'release/**'

jobs:
  release_ping-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: ping
          # @todo change to true
          dry-run: false
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

  release_prepare-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: prepare
          # @todo change to true
          dry-run: false
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

  release_release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: release
          # @todo change to true
          dry-run: false
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
