name: release_test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/release_test.yml'
      - 'lib/github.ts'
      - 'release/**'

jobs:
  release_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: ping
  test-prepare:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: prepare
  test-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./release
        with:
          mode: release
