name: release_test

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/release_test.yml'
      - 'lib/conventionalCommits.ts'
      - 'lib/git.ts'
      - 'lib/github.ts'
      - 'lib/semver.ts'
      - 'release/**'

jobs:
  release_ping-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./release
        with:
          mode: ping
          # @todo change to true
          dry-run: false
          gh-token: ${{ secrets.GH_BOT_TOKEN }}

  release_prepare-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./release
        with:
          mode: prepare
          dry-run: true
          lockfile: fixtures/release/exivity.lock
          changelog: fixtures/release/CHANGELOG.md
          repositories: fixtures/release/repositories.json
          pr-template: fixtures/release/NEW_RELEASE_PR_TEMPLATE.md
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
          jira-username: ${{ secrets.JIRA_BOT_EMAIL }}
          jira-token: ${{ secrets.JIRA_BOT_TOKEN }}
      - name: inspect lockfile
        run: cat fixtures/release/exivity.lock || true
      - name: inspect changelog
        run: cat fixtures/release/CHANGELOG.md || true

  release_release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./release
        with:
          mode: release
          dry-run: true
          lockfile: fixtures/release/exivity.lock
          repositories: fixtures/release/repositories.json
          gh-token: ${{ secrets.GH_BOT_TOKEN }}
          jira-username: ${{ secrets.JIRA_BOT_EMAIL }}
          jira-token: ${{ secrets.JIRA_BOT_TOKEN }}
