name: review

on:
  push:
    paths:
      - '.github/workflows/review.yml'
      - 'review/**'
      - 'lib/github.ts'

env:
  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./review
