name: semantic-pull-request_test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request_test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./semantic-pull-request
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
