name: test

on: push

jobs:
  test-init-ssh:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: exivity/actions/init-ssh@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
