name: virustotal_check-test

on:
  push:
    paths:
      - '.github/workflows/virustotal_check-test.yml'
      - 'virustotal/**'
  workflow_dispatch:
  schedule:
    - cron: '45 3 * * *'

jobs:
  virustotal_check-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./virustotal
        with:
          mode: check
          virustotal-api-key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
